# Ejemplo de convolución y pooling a mano 

para una matriz de 5x5 con ventanas de 3x3 y un paso de 1

In [ ]:
Creamos una matriz de 5x5 con aleatorios entre 0 y 1 como valores

In [36]:
import numpy as np
#original = np.zeros((5,5))
original = np.random.randint(0,2,(5,5))
print(original)

[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [1 1 0 0 1]
 [1 0 0 0 0]]


se usa porcionamiento para crear la lista de ventanas

In [37]:
ventanas = []
for i in range(3):
    for j in range(3):
        ventanas.append(original[i:i+3,j:j+3])

for v in ventanas:
    print(v)

[[1 0 0]
 [0 1 0]
 [0 1 1]]
[[0 0 0]
 [1 0 1]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 1 0]]
[[0 1 0]
 [0 1 1]
 [1 1 0]]
[[1 0 1]
 [1 1 1]
 [1 0 0]]
[[0 1 0]
 [1 1 0]
 [0 0 1]]
[[0 1 1]
 [1 1 0]
 [1 0 0]]
[[1 1 1]
 [1 0 0]
 [0 0 0]]
[[1 1 0]
 [0 0 1]
 [0 0 0]]


se hace un max_pooling de cada ventana

In [40]:
resultado = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        if 1 in ventanas[i+j]:
            resultado[i,j] = 1
        else:
            resultado[i,j] = 0
print(resultado)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
